<a href="https://colab.research.google.com/github/dlyrikz/DeepLearning/blob/master/ANN_for_Binary_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 1: Installation and Setup

In [107]:
# Install Tensorflow
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#print(tf.__version__)

# Step 2: Data Preprocessing

In [108]:
# Importing the dataset
from google.colab import files
uploaded = files.upload()


Saving Churn_Modelling.csv to Churn_Modelling (2).csv


In [109]:
#print(uploaded)

In [110]:
# Check the working directory
! ls

'Churn_Modelling (1).csv'   Churn_Modelling.csv
'Churn_Modelling (2).csv'   sample_data


In [111]:
# Reading the file
dataset = pd.read_csv('Churn_Modelling.csv')

In [112]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [113]:
# Selecting the independent and dependent variables
# axis = 0 (rows) 1 (cols)

x = dataset.drop(labels=['RowNumber', 'CustomerId','Surname','Exited'], axis=1)   #independent variables
y = dataset['Exited']                                                             #dependent variable



In [114]:
# Check the variables
x.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [115]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [116]:
# Encoding the categorical data
from sklearn.preprocessing import LabelEncoder

In [117]:
label_1 = LabelEncoder()
x['Geography'] = label_1.fit_transform(x['Geography'])

In [118]:
x.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [119]:
label_2 = LabelEncoder()
x['Gender'] = label_2.fit_transform(x['Gender'])

In [120]:
x.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [121]:
# IMPORTANT - no comparison in Categorical Data 0 <> 1 <> 2
# AVOIDING DUMMY VARIABLE TRAP

x = pd.get_dummies(x, drop_first=True, columns=['Geography'])

# check the data
x.head(8)

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1
5          645       1   44  ...        149756.71            0            1
6          822       1   50  ...         10062.80            0            0
7          376       0   29  ...        119346.88            1            0

[8 rows x 11 columns]

In [122]:
# Split the dataset into Train and Test sets
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Feature Scaling - Due to the wide range in dataset values

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# check the transform values should be between 0 -1
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
         1.75486502, -0.57369368]])

In [123]:
x_test


array([[-0.55204276, -1.09168714, -0.36890377, ...,  1.61085707,
         1.75486502, -0.57369368],
       [-1.31490297, -1.09168714,  0.10961719, ...,  0.49587037,
        -0.5698444 , -0.57369368],
       [ 0.57162971, -1.09168714,  0.30102557, ..., -0.42478674,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227,  0.91601335, -0.27319958, ...,  0.71888467,
        -0.5698444 ,  1.74309049],
       [-0.00566991,  0.91601335, -0.46460796, ..., -1.54507805,
         1.75486502, -0.57369368],
       [-0.79945688,  0.91601335, -0.84742473, ...,  1.61255917,
         1.75486502, -0.57369368]])

# Step 3: Build the Model

In [124]:
# Intializing the ANN
# Creating an object

model = tf.keras.models.Sequential()

In [125]:
# Add Input Layer and 1st Hidden Layer
# 1) Units = 6 *** Trick formula = AVG(input + output dimension) 
# 2) Activation function = ReLU
# 3) Input dimension = 11

model.add(tf.keras.layers.Dense(units=6, activation='relu', input_dim = 11))

In [126]:
# Add 2nd Hidden Layer

model.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [127]:
# Add Output Layer
# 1) Use activation = sigmoid used for Binary class.

model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [128]:
# Compiling the Model
# 1) Optimizer - adam, (minimize the loss function)
# 2) loss function = binary_crossentropy (acts as guide to optimizer)
# 3) matrices = accuracy  ***Tip for Binary use categorical_accuracy
 
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [129]:
# Check Summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


# Step 4: Training the Model

In [130]:
# Tips: x_train is numpy array and y_train is vector
#       Convert y_train to numpy

model.fit(x_train, y_train.to_numpy(), batch_size=10, epochs=20)

Epoch 1/20
800/800 [==============================] - 1s 1ms/step - loss: 0.5133 - accuracy: 0.7794
Epoch 2/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4491 - accuracy: 0.7951
Epoch 3/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4232 - accuracy: 0.8085
Epoch 4/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3950 - accuracy: 0.8288
Epoch 5/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3753 - accuracy: 0.8425
Epoch 6/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3629 - accuracy: 0.8491
Epoch 7/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3567 - accuracy: 0.8505
Epoch 8/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3526 - accuracy: 0.8550
Epoch 9/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3499 - accuracy: 0.8540
Epoch 10/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3481 - accuracy: 0.8572

# Step 5: Model Evaluation and Prediction

In [131]:
# Evaluate Model

test_loss, test_accuracy = model.evaluate(x_test, y_test.to_numpy())

63/63 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8650


In [132]:
print('Test Accuracy {}: '.format(test_accuracy))

Test Accuracy 0.8650000095367432: 


In [133]:
# Make the Prediction
y_predict = model.predict_classes(x_test)
print(y_predict)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [134]:
print(y_test)

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64


In [135]:
y_test = y_test.to_numpy()

In [136]:
print(y_predict[8]), print(y_test[8])

[0]
1


(None, None)

In [137]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predict)
print(cm)

[[1532   63]
 [ 207  198]]


In [138]:
accuracy_cm = accuracy_score(y_test, y_predict)
print(accuracy_cm)

0.865
